### ISSUE TITLE
jupyter build error: jupyter_client.kernelspec.NoSuchKernel: No such kernel named sparql

### ISSUE THREAD

**Issue by oising** [BrickSchema/docs#2]
![image](https://user-images.githubusercontent.com/1844001/110721603-de771100-81de-11eb-808c-182b6b0607d9.png)

**Comment by oising** [comment]
ok, stumbled around google until I found https://github.com/paulovn/sparql-kernel 

Did:


```
pip install sparqlkernel
jupyter sparqlkernel install
```
which _mostly_ worked:

![image](https://user-images.githubusercontent.com/1844001/110722300-0155f500-81e0-11eb-9717-6da09da9c607.png)

so now jupyter seems to have what it needs, but it still won't compile the html:

![image](https://user-images.githubusercontent.com/1844001/110722135-cc49a280-81df-11eb-8d06-07e6458cd0e8.png)

I'm running python 3.9.

**Comment by oising** [comment]
ok, I figured it out -- python3 asyncio library is not implemented completely on windows. I switched to WSL and got it working, but regardless - you guys should also put the instructions for installing kernelsparql into jupyter.

**Comment by gtfierro** [comment]
Sorry for the late reply! For some reason I'm not getting notifications on many of the repos anymore.

Thanks for the time you spent digging into the issue; it is too bad there is a dependency on asyncio that isn't functional on Windows. Hopefully that is something that gets remedied soon!

I've updated the README to include these instructions: https://github.com/BrickSchema/docs/commit/9837c9320369c8c3dd073da974263a1a2147b268
