### ISSUE TITLE
Add documentation on how to model pipes, ducts, etc

### ISSUE THREAD

**Issue by sarahmacSE978** [BrickSchema/docs#20]
I often get questions on how to model points related to a system that has pipes, ducts, etc.  It will be helpful to have documentation on this. Thanks!

**Comment by gtfierro** [comment]
Let me know if you like the new docs! 

https://docs.brickschema.org/modeling/connections.html

Happy to add anything you feel it is missing. I did have to fix a couple things in Brick, which will be addressed in https://github.com/BrickSchema/Brick/actions/runs/9588676415/job/26441179889?pr=642
