### ISSUE TITLE
Issue on page /lifecycle/creation.html

### ISSUE THREAD

**Issue by BrutalSimplicity** [BrickSchema/docs#8]
This page appears to only be visible from https://docs.brickschema.org/intro.html.

Any of the subtopics do not have the subheading "Creating a Brick Model"

**Comment by BrutalSimplicity** [comment]
Perhaps a caching issue:
https://jupyterbook.org/start/build.html#source-vs-build-files

**Comment by gtfierro** [comment]
Good catch! Applying the `--all` flag seemed to do the trick. Thanks for taking the time to file the issue!
