### ISSUE TITLE
[question] model example ttl file 

### ISSUE THREAD

**Issue by wta12** [BrickSchema/docs#9]
Hi, I have some questions about Brick example file. Please let me know if there is a better place to ask questions about Brick schema: 

- How to get the model example file image ([here](https://github.com/BrickSchema/docs/blob/main/img/brick-model-example.png)) as rendering output from Brick Viewer/Studio or it's just a demo created artificially ?  

- Is it possible to  programmatically arrange and pick shape of Brick objects similar to example file image instead of simple array and ellipse shapes ?

**Comment by gtfierro** [comment]
Hi @wta12 

That first image was manually created in Google Drawings; it is a long-term goal of ours to enable nicer visualizations.

To your second question, if you use a tool like `graphviz`, it is possible to generate images that have custom images and shapes based on their attributes. Look at generating graphviz files in Python as a place to start
